// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// La CLI de Prisma solo carga .env por defecto; .env.local (donde vive
// DATABASE_URL real, siguiendo la convención de Next.js) se carga a mano.
config();
config({ path: ".env.local", override: true });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // La CLI (migrate/db pull/etc.) usa DIRECT_URL (modo sesión) — la app
  // corriendo usa DATABASE_URL (pooler en modo transacción) directo desde
  // src/lib/prisma.ts, no pasa por acá.
  datasource: {
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
